// ── Aether Mock Data Layer ──────────────────────────────────────────────────

export const RESEARCHER = {
  name: "Alex Chen",
  initials: "AC",
  streak: 11,
  papersToday: 3,
  paperTarget: 3,
  labmates: [
    { name: "Priya Nair", initials: "PN", color: "#7C6AF7" },
    { name: "James Wu", initials: "JW", color: "#F76A6A" },
    { name: "Sara Okonkwo", initials: "SO", color: "#6AF7C4" },
  ],
};

export const PAPERS = [
  {
    id: "p001",
    title: "FlashAttention-3: Fast and Accurate Attention with Asynchrony and Low-precision",
    authors: ["Tri Dao", "Daniel Y. Fu"],
    year: 2024,
    venue: "NeurIPS 2024",
    arxivId: "2407.08608",
    abstract: "We present FlashAttention-3, which introduces new techniques to speed up attention on GPUs that have asynchrony between different types of operations as well as supports for FP8 low-precision. We propose three main ideas: exploiting asynchrony of the Tensor Cores and TMA to overlap computation and data movement via warp-specialization; interleaving block-wise matmul and softmax operations; and incoherent processing that leverages hardware support for FP8 quantization. Together, FlashAttention-3 reaches 740–1090 TFLOPS/s on H100 GPUs, 1.5-2.0× faster than FlashAttention-2.",
    tags: ["attention", "transformers", "efficiency", "hardware"],
    status: "read", // read | unread | reading
    savedDate: "2025-01-15",
    readDate: "2025-01-16",
    highlights: [
      { id: "h001", text: "reaches 740–1090 TFLOPS/s on H100 GPUs", type: "result", note: "Key benchmark to compare against" },
      { id: "h002", text: "warp-specialization", type: "method", note: "Core technique - overlapping compute and memory" },
      { id: "h003", text: "1.5-2.0× faster than FlashAttention-2", type: "result", note: null },
    ],
    summary4: {
      claim: "FP8 + async overlap can achieve 1.5-2× speedup over FA2 on H100",
      method: "Warp-specialized pipelines interleaving matmul/softmax with TMA asynchrony",
      dataset: "H100 GPUs, standard attention benchmarks",
      limitation: "Benefits are hardware-specific; requires H100 Tensor Core features"
    },
    citations: ["p003", "p004", "p007"],
    citedBy: ["p002", "p006"],
    similarTo: ["p003", "p004", "p005"],
    noveltyScore: 0.72,
    baselines: [
      { dataset: "H100 attention benchmark", metric: "TFLOPS/s", score: "1090", method: "FlashAttention-3" },
      { dataset: "H100 attention benchmark", metric: "TFLOPS/s", score: "520", method: "FlashAttention-2" },
    ],
    labmateReads: ["PN"],
    x: 420, y: 280, // graph coordinates
  },
  {
    id: "p002",
    title: "Ring Attention with Blockwise Transformers for Near-Infinite Context",
    authors: ["Hao Liu", "Matei Zaharia", "Pieter Abbeel"],
    year: 2023,
    venue: "ICLR 2024",
    arxivId: "2310.01889",
    abstract: "We present Ring Attention with Blockwise Transformers, which enables training and inference of sequences that are many times longer than possible with prior memory-efficient Transformers. We achieve this by leveraging distributed computing and using parallelism to compute attention across devices simultaneously. Our approach uses a ring-shaped communication pattern to distribute and compute attention across an arbitrary number of devices, while maintaining correctness of full sequence attention.",
    tags: ["long context", "distributed training", "attention", "efficiency"],
    status: "read",
    savedDate: "2025-01-10",
    readDate: "2025-01-12",
    highlights: [
      { id: "h004", text: "ring-shaped communication pattern to distribute and compute attention", type: "method", note: "Elegant solution to context length limit" },
      { id: "h005", text: "sequences that are many times longer than possible with prior", type: "claim", note: null },
    ],
    summary4: {
      claim: "Ring topology enables near-infinite context via device parallelism",
      method: "Circular attention shards distributed across GPU ring with overlap",
      dataset: "Language modeling benchmarks up to 1M tokens",
      limitation: "Communication overhead scales with number of devices"
    },
    citations: ["p001", "p003", "p007"],
    citedBy: ["p006"],
    similarTo: ["p001", "p003"],
    noveltyScore: 0.61,
    baselines: [],
    labmateReads: ["JW", "PN"],
    x: 580, y: 180,
  },
  {
    id: "p003",
    title: "Attention Is All You Need",
    authors: ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar", "Jakob Uszkoreit", "Llion Jones", "Aidan N. Gomez", "Łukasz Kaiser", "Illia Polosukhin"],
    year: 2017,
    venue: "NeurIPS 2017",
    arxivId: "1706.03762",
    abstract: "We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train.",
    tags: ["transformers", "attention", "machine translation", "foundational"],
    status: "read",
    savedDate: "2024-06-01",
    readDate: "2024-06-02",
    highlights: [
      { id: "h006", text: "dispensing with recurrence and convolutions entirely", type: "claim", note: "The paradigm shift" },
      { id: "h007", text: "more parallelizable and requiring significantly less time to train", type: "result", note: null },
    ],
    summary4: {
      claim: "Pure attention architecture outperforms RNNs on translation tasks",
      method: "Multi-head self-attention with positional encodings",
      dataset: "WMT 2014 EN-DE and EN-FR translation",
      limitation: "Quadratic complexity in sequence length"
    },
    citations: [],
    citedBy: ["p001", "p002", "p004", "p005"],
    similarTo: ["p004", "p001"],
    noveltyScore: 0.15,
    baselines: [
      { dataset: "WMT 2014 EN-DE", metric: "BLEU", score: "28.4", method: "Transformer (base)" },
      { dataset: "WMT 2014 EN-FR", metric: "BLEU", score: "41.0", method: "Transformer (big)" },
    ],
    labmateReads: ["PN", "JW", "SO"],
    x: 300, y: 420,
  },
  {
    id: "p004",
    title: "Efficient Transformers: A Survey",
    authors: ["Yi Tay", "Mostafa Dehghani", "Dara Bahri", "Donald Metzler"],
    year: 2022,
    venue: "ACM Computing Surveys",
    arxivId: "2009.06732",
    abstract: "Transformers have become the defacto standard for many NLP problems and have found wide applications in computer vision, speech, and even chemistry. However, Transformers suffer from quadratic complexity with respect to sequence length. This survey conducts a comprehensive review of the various efforts that have been put into improving Transformer efficiency.",
    tags: ["survey", "transformers", "efficiency", "attention"],
    status: "read",
    savedDate: "2024-09-05",
    readDate: "2024-09-07",
    highlights: [
      { id: "h008", text: "quadratic complexity with respect to sequence length", type: "limitation", note: "Core bottleneck motivating my work" },
    ],
    summary4: {
      claim: "Comprehensive taxonomy of 20+ efficient attention mechanisms",
      method: "Literature survey with unified notation",
      dataset: "LRA benchmark for comparison",
      limitation: "Survey coverage ends at 2022 — many recent works missing"
    },
    citations: ["p003"],
    citedBy: ["p001", "p002"],
    similarTo: ["p001", "p002", "p003"],
    noveltyScore: 0.18,
    baselines: [],
    labmateReads: ["SO"],
    x: 180, y: 300,
  },
  {
    id: "p005",
    title: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
    authors: ["Albert Gu", "Tri Dao"],
    year: 2023,
    venue: "ICLR 2024",
    arxivId: "2312.00752",
    abstract: "Foundation models, now powering most of the exciting applications in deep learning, are almost universally based on the Transformer architecture and its core attention module. While many subquadratic-time architectures such as linear attention and state space models have been developed to address Transformers' computational inefficiency on long sequences, they have been on a step behind attention in terms of quality. We propose Mamba, a new architecture with a selective state space model. Mamba achieves throughput 5× higher than Transformers and linear scaling in sequence length.",
    tags: ["state space models", "efficiency", "sequence modeling", "mamba"],
    status: "unread",
    savedDate: "2025-01-18",
    readDate: null,
    highlights: [],
    summary4: null,
    citations: ["p003", "p004"],
    citedBy: ["p006"],
    similarTo: ["p001", "p002", "p003"],
    noveltyScore: 0.81,
    baselines: [
      { dataset: "Pile perplexity", metric: "PPL", score: "7.98", method: "Mamba 3B" },
    ],
    labmateReads: ["JW"],
    x: 520, y: 380,
  },
  {
    id: "p006",
    title: "Jamba: A Hybrid Transformer-Mamba Language Model",
    authors: ["Opher Lieber", "Barak Lenz", "Hofit Bata", "Gal Cohen"],
    year: 2024,
    venue: "arXiv 2024",
    arxivId: "2403.19887",
    abstract: "We present Jamba, a new production-grade large language model based on a novel hybrid Transformer-Mamba mixture-of-experts architecture. Jamba interleaves blocks of Transformer and Mamba layers, jointly with mixture-of-experts (MoE) modules, providing flexibility to balance efficiency and quality. With 256K context length and throughput 3× higher than competing models, Jamba demonstrates that hybrid approaches can achieve both quality and efficiency.",
    tags: ["hybrid architecture", "mamba", "transformers", "MoE", "efficiency"],
    status: "unread",
    savedDate: "2025-01-20",
    readDate: null,
    highlights: [],
    summary4: null,
    citations: ["p001", "p002", "p005"],
    citedBy: [],
    similarTo: ["p005", "p001"],
    noveltyScore: 0.88,
    baselines: [
      { dataset: "MMLU", metric: "Accuracy", score: "67.4", method: "Jamba" },
    ],
    labmateReads: [],
    x: 650, y: 300,
  },
  {
    id: "p007",
    title: "Scalable MatMul-free Language Modeling",
    authors: ["Rui-Jie Zhu", "Yu Zhang", "Ethan Sifferman", "Tyler Sheaves"],
    year: 2024,
    venue: "arXiv 2024",
    arxivId: "2406.02528",
    abstract: "Matrix multiplication (MatMul) operations dominate the computational cost of modern large language models (LLMs). In this paper, we show that MatMul operations can be completely eliminated from LLMs while maintaining strong performance. Our method achieves competitive results on language modeling tasks while reducing GPU memory usage significantly.",
    tags: ["efficiency", "matmul-free", "language models", "hardware"],
    status: "unread",
    savedDate: "2025-01-21",
    readDate: null,
    highlights: [],
    summary4: null,
    citations: ["p003", "p004"],
    citedBy: ["p001"],
    similarTo: ["p001", "p005"],
    noveltyScore: 0.94,
    baselines: [],
    labmateReads: [],
    x: 380, y: 150,
  },
];

export const ALERTS = [
  {
    id: "a001",
    severity: "red",
    severityLabel: "HIGH OVERLAP",
    title: "Potential Conflict Detected",
    paper: "Linear Attention via Kernel Decomposition for Efficient Transformers",
    authors: ["Wei Chen", "Liu Yang"],
    arxivId: "2501.09234",
    similarity: 84,
    topic: "Efficient Attention Mechanisms",
    detectedAt: "2 hours ago",
    reason: "Addresses same efficiency-quality tradeoff using similar kernel approximation approach. Method section overlaps significantly with your monitored abstract.",
    read: false,
  },
  {
    id: "a002",
    severity: "yellow",
    severityLabel: "TANGENTIAL",
    title: "Related Work Published",
    paper: "Sparse Attention Patterns in Production LLM Serving",
    authors: ["Alicia Romero", "Kevin Park"],
    arxivId: "2501.08891",
    similarity: 52,
    topic: "Attention Efficiency",
    detectedAt: "Yesterday",
    reason: "Explores attention sparsity from serving angle; different problem framing but shares evaluation benchmarks.",
    read: false,
  },
  {
    id: "a003",
    severity: "blue",
    severityLabel: "CITATION",
    title: "Paper You're Reading Got Cited",
    paper: "Memory-Efficient Attention via Optimal Tiling Strategies",
    authors: ["Sara Kim"],
    arxivId: "2501.07654",
    similarity: 31,
    topic: "FlashAttention",
    detectedAt: "3 days ago",
    reason: "New paper cites FlashAttention-3 (p001) in related work. Builds on memory tiling analysis.",
    read: true,
  },
];

export const MONITORS = [
  {
    id: "m001",
    name: "Efficient Attention Mechanisms",
    type: "topic",
    query: "efficient attention transformers linear complexity",
    active: true,
    alertCount: 2,
    weeklyVolume: 14,
    trend: "rising",
  },
  {
    id: "m002",
    name: "State Space Models",
    type: "topic",
    query: "state space models selective SSM Mamba",
    active: true,
    alertCount: 1,
    weeklyVolume: 8,
    trend: "stable",
  },
  {
    id: "m003",
    name: "My Draft Abstract",
    type: "abstract",
    query: "We propose a hardware-aware attention mechanism that exploits asynchronous memory access patterns to achieve subquadratic complexity while maintaining full attention semantics on modern GPU architectures.",
    active: true,
    alertCount: 1,
    weeklyVolume: null,
    similarityHistory: [22, 18, 31, 45, 52, 48, 84],
    trend: "rising",
  },
  {
    id: "m004",
    name: "Tri Dao",
    type: "author",
    query: "Tri Dao",
    active: true,
    alertCount: 0,
    weeklyVolume: 2,
    trend: "stable",
  },
];

export const FEED_ITEMS = [
  {
    type: "threat",
    title: "Threat Detected",
    subtitle: "New paper may overlap with your current research",
    paperId: null,
    paperTitle: "Linear Attention via Kernel Decomposition for Efficient Transformers",
    similarity: 84,
    timestamp: "2 hours ago",
  },
  {
    type: "validates",
    title: "Your Hypothesis Validated",
    subtitle: "A paper aligned with your saved work gained significant traction",
    paperId: "p001",
    paperTitle: "FlashAttention-3",
    metric: "+47 citations this week",
    timestamp: "Yesterday",
  },
  {
    type: "unread",
    title: "Unfinished Reading",
    paperId: "p005",
    paperTitle: "Mamba: Linear-Time Sequence Modeling",
    progress: 0,
    savedDate: "3 days ago",
  },
  {
    type: "new",
    title: "New in Efficient Attention",
    papers: ["p006", "p007"],
    count: 2,
    since: "yesterday",
  },
];

export const LIT_CLUSTERS = [
  {
    id: "c001",
    name: "Foundational Transformers",
    color: "#7C6AF7",
    papers: ["p003", "p004"],
    draft: "Early approaches to sequence modeling (Vaswani et al., 2017; Tay et al., 2022) established the Transformer architecture as the dominant paradigm. These methods introduced multi-head self-attention as a replacement for recurrence, achieving strong parallelizability. However, they suffered from quadratic complexity in sequence length, motivating subsequent efficiency research.",
  },
  {
    id: "c002",
    name: "Hardware-Aware Attention",
    color: "#F7A26A",
    papers: ["p001", "p002"],
    draft: "Hardware-aware attention mechanisms (Dao & Fu, 2024; Liu et al., 2023) addressed memory bandwidth bottlenecks through IO-aware algorithms. FlashAttention-3 leverages asynchronous tensor operations to achieve 1.5-2× speedups, while Ring Attention distributes computation across device topologies to enable near-infinite context lengths.",
  },
  {
    id: "c003",
    name: "Alternative Architectures",
    color: "#6AF7C4",
    papers: ["p005"],
    draft: "Alternative sequence architectures challenge attention's dominance. Mamba (Gu & Dao, 2023) demonstrates that selective state spaces can match Transformer quality with linear-time complexity, achieving 5× throughput improvements on long sequences.",
  },
];

export const PAPER_SECTIONS = {
  p001: [
    { id: "s1", title: "Abstract", summary: "FP8 + async warp specialization achieves 1.5-2× speedup over FA2 on H100." },
    { id: "s2", title: "1. Introduction", summary: "GPU memory bandwidth is the bottleneck; asynchrony between compute units is underexplored." },
    { id: "s3", title: "2. Background", summary: "Reviews FA2 tiling strategy and H100 Tensor Core / TMA architecture." },
    { id: "s4", title: "3. FlashAttention-3", summary: "Three techniques: warp-specialization, interleaved softmax-matmul, incoherent FP8 processing." },
    { id: "s5", title: "4. Experiments", summary: "740–1090 TFLOPS/s on H100; perplexity parity with BF16 baseline at FP8." },
    { id: "s6", title: "5. Related Work", summary: "Positions against FlashAttention-1/2, cuBLAS, and Triton kernels." },
    { id: "s7", title: "6. Conclusion", summary: "Hardware-software co-design is necessary for attention efficiency at scale." },
  ],
};
